### ISSUE TITLE
Question: what package to install

### ISSUE THREAD

**Issue by vitalikda** [radix-ui/icons#104]
https://www.npmjs.com/package/@radix-ui/react-icons

Which of these is the correct package?
```
npm install @modulz/radix-icons
or
npm install @radix-ui/react-icons
```

**Comment by vladmoroz** [comment]
@vitalikda `npm install @radix-ui/react-icons` is the correct one. I guess you followed the outdated npm link on the website? Will fix it. 

Let me know if it's something else.

**Comment by vitalikda** [comment]
@vladmoroz thanks! 
Yes, looks like you have a typo on this page: https://www.npmjs.com/package/@radix-ui/react-icons
