### ISSUE TITLE
Request: Compatibility as cursors

### ISSUE THREAD

**Issue by penx** [radix-ui/icons#116]
I'd love to be able to use some of these icons as a cursor.

e.g.

```tsx
import pencil from @radix-ui/icons/pencil-1.svg?raw';

const CustomCursor = styled('div', {
  cursor: `url("data:image/svg+xml,${pencil}") 0 15, pointer`
}); 
```

However this would require:

1. creating a package `@radix-ui/icons` with the raw SVG icons _or_ including the raw SVG assets with the existing react-icons package (they are not bundled at present)/
2. dual tone icons, e.g. for the pencil having a black outline and a white fill - this is so that the icon would remain visible when moving between white and black background areas.

**Comment by vladmoroz** [comment]
Hi @penx, adapting the icons for cursors is a bit out of scope for this package since it might be a bit too niche and has a bunch of extra design constraints. Feel free to modify the icons for your project and use them as you see fit though.
