### ISSUE TITLE
Request: Google icon

### ISSUE THREAD

**Issue by zirlman** [radix-ui/icons#156]
I think it would be nice to have a Google icon, especially for SSO, since Sign in with Google is more common compared to Discord, that has its icon

**Comment by pschaub** [comment]
This could be a nice idea in combination with [the RFC 'Radix Auth'](https://github.com/radix-ui/primitives/pull/1978).

I think this kind of icons should be categorized as 'brand icons'.

**Comment by zirlman** [comment]
Nice proposal. Radix UI has made ny life so much easier. 

I'll close this issue since I saw on some other issue that this ineed falls under category of brand icons
