### ISSUE TITLE
Error installing package in NextJs app 15.0.0

### ISSUE THREAD

**Issue by rushidshinde** [radix-ui/icons#189]
Got this error while installing

PS C:\Rushi\Home\learn\nextjs\newblogsite> npm i @radix-ui/react-icons
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: newblogsite@0.1.0
npm error Found: react@19.0.0-rc-65a56d0e-20241020
npm error node_modules/react
npm error   react@"19.0.0-rc-65a56d0e-20241020" from the root project
npm error
npm error Could not resolve dependency:
npm error peer react@"^16.x || ^17.x || ^18.x" from @radix-ui/react-icons@1.3.0
npm error node_modules/@radix-ui/react-icons
npm error   @radix-ui/react-icons@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error C:\Users\rushi\AppData\Local\npm-cache\_logs\2024-10-22T14_16_16_835Z-eresolve-report.txt
npm error A complete log of this run can be found in: C:\Users\rushi\AppData\Local\npm-cache\_logs\2024-10-22T14_16_16_835Z-debug-0.log

Log report file:
[2024-10-22T14_16_16_835Z-eresolve-report.txt](https://github.com/user-attachments/files/17477790/2024-10-22T14_16_16_835Z-eresolve-report.txt)

![image](https://github.com/user-attachments/assets/ace3fcc0-b25f-4dfb-b24b-e58193295090)

Package.json file: 

{
  "name": "newblogsite",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "class-variance-authority": "^0.7.0",
    "clsx": "^2.1.1",
    "lucide-react": "^0.453.0",
    "next": "15.0.0",
    "react": "19.0.0-rc-65a56d0e-20241020",
    "react-dom": "19.0.0-rc-65a56d0e-20241020",
    "tailwind-merge": "^2.5.4",
    "tailwindcss-animate": "^1.0.7"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "eslint": "^8",
    "eslint-config-next": "15.0.0",
    "postcss": "^8",
    "tailwindcss": "^3.4.1",
    "typescript": "^5"
  }
}

**Comment by lukas-cc** [comment]
This PR will resolve this: https://github.com/radix-ui/icons/pull/184

**Comment by priyeshghamandi** [comment]
Please merge this PR to fix the issue https://github.com/radix-ui/icons/pull/184

**Comment by napstar-420** [comment]
The PR https://github.com/radix-ui/icons/pull/184 was opened on Aug 26, today is Oct 29 and it's still not merged, can you imagine the number of projects affected from this :(

**Comment by chaance** [comment]
Closed by https://github.com/radix-ui/icons/pull/184
