### ISSUE TITLE
request: flex align-items icon

### ISSUE THREAD

**Issue by joebnb** [radix-ui/icons#63]
appreciate for previous work #46 it's help me a lot ,but now now some new probelm appear. icon pack can't find a suitable icon to express flex 'align-items'.could implement it in spare time

![image](https://user-images.githubusercontent.com/1646883/105324405-57f27a00-5c06-11eb-9937-a429342af6ee.png)

**Comment by joebnb** [comment]
![image](https://user-images.githubusercontent.com/1646883/105326027-3d210500-5c08-11eb-9afd-a3b436de0e3e.png)


https://css-tricks.com/snippets/css/a-guide-to-flexbox/  this link may help to invention

**Comment by vladmoroz** [comment]
Have you looked into using the new align left, center, right, etc. icons for flex properties like align-items and justify-content?
They pretty much match previous align-items icons graphically.

**Comment by joebnb** [comment]
> Have you looked into using the new align left, center, right, etc. icons for flex properties like align-items and justify-content?
> They pretty much match previous align-items icons graphically.

yes,i'm worried about user may confused same icon display but different behavior will action, these icon maks some different may better.


here is a gif the 1st buttons control justify-contents(control each item how to order each other),2st buttons control align-items(control all item how to align parent container)

![2021-01-21 17-27-37 2021-01-21 17_28_10](https://user-images.githubusercontent.com/1646883/105331280-3bf2d680-5c0e-11eb-8116-f48a74378af7.gif)

**Comment by vladmoroz** [comment]
@joebnb justify-content can be done with align top icon and align bottom icon in your case. There's also two sets of align center, stretch, space-between, etc. icons for different orientations, so what you are doing should be possible with existing designs.

**Comment by joebnb** [comment]
![image](https://user-images.githubusercontent.com/1646883/105659055-cc793180-5f02-11eb-8418-06a246b6cdc9.png)
align bottom and top used in vertical mode.


i found on your site https://modulz.app/ we are doing pretty much same thing in different country😀
