### ISSUE TITLE
Why 15x15?

### ISSUE THREAD

**Issue by jossmac** [radix-ui/icons#82]
Curious to know how you arrived at these base dimensions, rather than the more popular 16x16. I assume it has something to do with "crispness", forcing most lines to fall on physical pixels?

**Comment by alinnert** [comment]
I can assume that's because it's easier to center 1px wide lines. With an odd number of pixels you have a center pixel row and column. With 16x16 you cannot perfectly center lines or objects like arrows or `+` if they have a width of 1px.

**Comment by colmtuite** [comment]
You are both correct.
