### ISSUE TITLE
Search input field breaks site

### ISSUE THREAD

**Issue by andrevenancio** [radix-ui/icons#83]
If you type `?` in the search input field if breaks the site and a message saying `An unexpected error has occurred.` shows up.

**Comment by jwarnox** [comment]
Typing `+` and `\` also breaks the site

**Comment by VaibhavAcharya** [comment]
![Error Screenshot](https://user-images.githubusercontent.com/41478382/128120483-324ee253-687a-4288-b766-415e183365cd.PNG)

Issue: [Javascript + Regex = Nothing To Repeat Error](https://stackoverflow.com/questions/6288181/javascript-regex-nothing-to-repeat-error)
